[build]
  command = "npm run build && cp -r src/supabase netlify/functions/dist/supabase"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"  # Localização das funções Netlify

[[redirects]]
  from = "/api/*"  # Redireciona qualquer requisição para o caminho /api/
  to = "/.netlify/functions/:splat"  # Redireciona para a função Netlify
  status = 200


