# netlify.toml

[build]
  command = "npm run build && [ -d src/supabase ] && cp -r src/supabase netlify/functions/dist/supabase || echo '📂 Pasta src/supabase não encontrada, pulando cópia...'"
  publish = "dist"
  functions = "netlify/functions"


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
