# netlify.toml

[build]
  command = "npm run build && cp -r src/supabase netlify/functions/dist/supabase"  # Compila e copia os tipos Supabase para funções
  publish = "dist"  # Diretório de saída do frontend
  functions = "netlify/functions"
  
[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
